apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: ado1
  annotations:
    backstage.io/kubernetes-id: ado1
    devops.jio.com/project-repo: T2R/T2R
    devops.jio.com/project: T2R
    devops.jio.com/build-definition: jio-t2r-dynamic-tkt-configurator-admin-bff-service
spec:
  type: service
  lifecycle: unknown
  owner: guests
